import { Ionicons } from '@expo/vector-icons';
import { useQuery } from '@tanstack/react-query';
import { router, useLocalSearchParams } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { productQuery } from '@/features/catalog/api/catalog.api';
import { colors, radii, spacing, typography } from '@/theme/tokens';
import { CartButton } from '@/features/cart/components/CartButton';
import { useCartStore } from '@/features/cart/store/cart.store';

const peso=(value:number)=>`₱${value.toLocaleString('en-PH',{minimumFractionDigits:2})}`;
export default function ProductDetailsScreen(){const {id}=useLocalSearchParams<{id:string}>();const product=useQuery(productQuery(id));const addItem=useCartStore((state)=>state.addItem);if(product.isPending)return <SafeAreaView style={styles.safe}><ActivityIndicator style={styles.center} color={colors.primary}/></SafeAreaView>;if(product.isError)return <SafeAreaView style={styles.safe}><Text style={styles.center}>Product not found.</Text></SafeAreaView>;const item=product.data;return <SafeAreaView style={styles.safe} edges={['top']}><View style={styles.header}><Pressable onPress={()=>router.back()}><Ionicons name="arrow-back" size={24} color={colors.textPrimary}/></Pressable><Text style={styles.headerTitle}>Product Details</Text><CartButton/></View><ScrollView contentContainerStyle={styles.content}><View style={styles.visual}><Ionicons name="ellipse-outline" size={100} color={colors.textPrimary}/></View><Text style={styles.brand}>{item.brand.toUpperCase()}</Text><Text style={styles.name}>{item.name}</Text><View style={styles.chip}><Text style={styles.chipText}>{item.tireSize.display}</Text></View><Text style={styles.price}>{peso(item.price.promo??item.price.srp)}</Text>{item.price.promo!==null&&<Text style={styles.srp}>{peso(item.price.srp)}</Text>}<Text style={styles.stock}>{item.stock===null?'Availability confirmed during checkout':`${item.stock} in stock`}</Text><View style={styles.actions}><Pressable style={styles.secondaryCta} onPress={()=>addItem(item,4)}><Text style={styles.secondaryCtaText}>Add Set of 4</Text></Pressable><Pressable style={styles.cta} onPress={()=>addItem(item)}><Text style={styles.ctaText}>Add to Cart</Text></Pressable></View></ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},center:{flex:1,textAlign:'center',textAlignVertical:'center'},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:spacing.lg,borderBottomWidth:1,borderBottomColor:colors.border},headerTitle:{...typography.h2},content:{padding:spacing.xl},visual:{height:190,alignItems:'center',justifyContent:'center',backgroundColor:colors.surfaceTint,borderRadius:radii.lg,marginBottom:spacing.xl},brand:{fontSize:12,fontWeight:'800',letterSpacing:1,color:colors.primary},name:{...typography.h1,marginTop:spacing.sm},chip:{alignSelf:'flex-start',backgroundColor:colors.surfaceTint,borderRadius:radii.pill,paddingHorizontal:spacing.md,paddingVertical:5,marginTop:spacing.md},chipText:{fontWeight:'700',color:colors.textPrimary},price:{...typography.price,marginTop:spacing.xl},srp:{color:colors.strikethrough,textDecorationLine:'line-through'},stock:{color:colors.success,fontWeight:'700',marginTop:spacing.md},actions:{flexDirection:'row',gap:spacing.sm,marginTop:spacing.xl},cta:{flex:1,backgroundColor:colors.primary,borderRadius:radii.md,alignItems:'center',padding:16},ctaText:{color:colors.textOnPrimary,fontWeight:'800',fontSize:14},secondaryCta:{flex:1,borderWidth:1,borderColor:colors.primary,borderRadius:radii.md,alignItems:'center',padding:16},secondaryCtaText:{color:colors.primary,fontWeight:'800',fontSize:14}});
